name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          path: main
          persist-credentials: false
      - name: Checkout Data
        uses: actions/checkout@master # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          repository: CodeforNepal/fellowship-data
          token: ${{ secrets.PAT }}
          path: data
          persist-credentials: false
      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cp -r ./data/data_literacy/_contents ./main
      - run: cd ./main && yarn
      - run: cd ./main && yarn build
        env:
          NEXT_PUBLIC_FORM_URL: ${{ secrets.NEXT_PUBLIC_FORM_URL }}
          CI: true
      - run: cp -r ./main/out .
      - run: touch ./out/.nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          REPOSITORY_NAME: CodeforNepal/data-literacy-fellowship
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
